name: aros_staff
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.6
#  disign
  flutter_screenutil: ^5.9.0
  #for state management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  bloc_concurrency: ^0.3.0
  #for networking
  dio: ^5.3.2
  # for time
  intl: ^0.19.0
  #log
  logger: any
  #for local base
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  # Service Locator
  get_it: ^8.0.3
  # for check internet
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.0.0
  lottie: ^3.1.1
  # for navigation
  go_router: ^14.8.1
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.1
  fluttertoast: ^8.2.12
  geolocator: ^13.0.3
  syncfusion_flutter_gauges: ^29.1.33
  google_fonts: any
  flutter_svg: ^2.0.9
  app_settings: ^5.1.1
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
